web:
  build: .
  command: 'bash -c ''gunicorn django.wsgi'''
  volumes:
    - ./starseeker:/app/user
  environment:
    PORT: 8080
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
    MEMCACHEDCLOUD_SERVERS: 'memcachedcloud:11211'
  env_file:
    .env
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
    - memcachedcloud
shell:
  build: .
  command: bash
  volumes:
    - ./starseeker:/app/user
  environment:
    PORT: 8080
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
    MEMCACHEDCLOUD_SERVERS: 'memcachedcloud:11211'
  env_file:
    .env
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
    - memcachedcloud
herokuPostgresql:
  image: postgres:9.4
  env_file:
    .env
memcachedcloud:
  image: memcached
