# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 23:18
from __future__ import unicode_literals

import card.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('rarity', enumfields.fields.EnumIntegerField(enum=card.models.Card.Rarity)),
                ('card_type', enumfields.fields.EnumIntegerField(enum=card.models.Card.CardType)),
                ('cost', models.IntegerField()),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('health', models.IntegerField(blank=True, null=True)),
                ('effect', models.CharField(blank=True, default='', max_length=255)),
                ('collectible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('block_type', enumfields.fields.EnumIntegerField(enum=card.models.CardBlock.BlockType)),
            ],
        ),
        migrations.CreateModel(
            name='CardMechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.CardBlock'),
        ),
        migrations.AddField(
            model_name='card',
            name='hero_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='card.HeroClass'),
        ),
        migrations.AddField(
            model_name='card',
            name='mechanics',
            field=models.ManyToManyField(to='card.CardMechanic'),
        ),
        migrations.AddField(
            model_name='card',
            name='tribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='card.Tribe'),
        ),
    ]
