# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ('-year',),
            },
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='cardblock',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='cardmechanic',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='heroclass',
            options={'ordering': ('name',), 'verbose_name_plural': 'Hero classes'},
        ),
        migrations.AlterModelOptions(
            name='tribe',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='card',
            name='mechanics',
            field=models.ManyToManyField(blank=True, to='card.CardMechanic'),
        ),
        migrations.AddField(
            model_name='standardyear',
            name='blocks',
            field=models.ManyToManyField(to='card.CardBlock'),
        ),
    ]
